<div class="line-hor"></div>
<div class="box">
    <div class="border-right">
        <div class="border-left">
            <div class="inner">
                <h3>Client<span> New</span></h3>
                <span class="messageRed"><?php echo $this->message ?></span>
                <form id="contacts-form" action="/clients/new" method="post">
                    <fieldset>
                        <div class="field">
                            <label>Firts Name:</label>
                            <input type="text" value="" name="fisrtName" />
                        </div>
                        <div class="field">
                            <label>Last Name:</label>
                            <input type="text" value="" name="lastName" />
                        </div>
                        <div class="field">
                            <label>Code:</label>
                            <input type="text" value="<?php echo substr(time(),0,8); ?>" name="code" readonly="readonly" />
                        </div>
                        <div class="field">
                            <label>Effective Date:</label>
                            <input type="text" value="" name="effectiveDate" />
                        </div>
                    </fieldset>
                        <div class="wrapper"> 
                            <a href="/clients/" class="link2"> 
                                <span> <span>List</span> </span> 
                            </a>
                            <button type="submit" class="link2"> 
                                <span> <span>Send</span> </span>
                            </button> 
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>