<div id="slogan">
    <div class="image png"></div>
    <div class="inside">
        <h2>We are breaking<span>All Limitations</span></h2>
        <p>This is your place to rent movies...</p>
        <div class="wrapper"><a href="#" class="link1"><span><span>Learn More</span></span></a></div>
    </div>
</div>
<div class="box">
    <div class="border-right">
        <div class="border-left">
            <div class="inner">
                <h3>Welcome to <b>Video</b> <span>Store</span></h3>
                <p></p>
                <div class="img-box1"><img src="images/1page-img1.jpg" alt="" />This is the place where you could rent all the movies you want at the lowest price in the market... <br/>Try it now!</div>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <h3>Fresh <span>Movies</span></h3>
    <ul class="movies">
        <li>
            <h4>Toy Story 3</h4>
            <img src="images/1page-img2.jpg" alt="" />
            <p></p>
            <div class="wrapper"><a href="#" class="link2"><span><span>Rent</span></span></a></div>
        </li>
        <li>
            <h4>Prince of Percia: Sands of Time</h4>
            <img src="images/1page-img3.jpg" alt="" />
            <p></p>
            <div class="wrapper"><a href="#" class="link2"><span><span>Rent</span></span></a></div>
        </li>
        <li class="last">
            <h4>The Twilight Saga: Eclipse</h4>
            <img src="images/1page-img4.jpg" alt="" />
            <p></p>
            <div class="wrapper"><a href="#" class="link2"><span><span>Rent</span></span></a></div>
        </li>
        <li class="clear">&nbsp;</li>
    </ul>
</div>
