<!DOCTYPE HTML>
<html lang="es">
    <head>
        <title>Video Store</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?php echo $this->baseUrl() ?>/css/style.css" rel="stylesheet" type="text/css" />
        <script src="<?php echo $this->baseUrl() ?>/js/jquery-1.4.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/script.js" type="text/javascript"></script>
        <!--[if lt IE 7]>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/ie_png.js"></script>
        <script type="text/javascript">ie_png.fix('.png, .link1 span, .link1');</script>
        <link href="<?php echo $this->baseUrl() ?>/css/ie6.css" rel="stylesheet" type="text/css" />
        <![endif]-->
    </head>
    <body id="page1">
        <!-- START PAGE SOURCE -->
        <div class="tail-top">
            <div class="tail-bottom">
                <div id="main">
                    <div id="header">
                        <div class="row-1">
                            <div class="fleft"><a href="#">Cinema <span>World</span></a></div>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl('index') ?>"><img src="images/icon1-act.gif" alt="" /></a></li>
                                <li><a href="<?php echo $this->baseUrl('contacts') ?>"><img src="images/icon2.gif" alt="" /></a></li>
                                <li><a href="<?php echo $this->baseUrl('sitemap') ?>"><img src="images/icon3.gif" alt="" /></a></li>
                            </ul>
                        </div>
                        <div class="row-2" id="menuTabs">
                            <ul>
                                <li><a href="<?php echo $this->baseUrl('index') ?>">Home</a></li>
                                <li><a href="<?php echo $this->baseUrl('about') ?>">About</a></li>
                                <li><a href="<?php echo $this->baseUrl('articles') ?>">Articles</a></li>
                                <li><a href="<?php echo $this->baseUrl('contacts') ?>">Contacts</a></li>
                                <li class="last"><a href="<?php echo $this->baseUrl('sitemap') ?>">Sitemap</a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="content">
                        <?php echo $this->layout()->content ?>
                    </div>
                    <div id="footer">
                        <div class="left">
                            <div class="right">
                                <div class="footerlink">
                                    <p class="lf">Copyright &copy; 2012 <a href="#">VideoStore</a> - All Rights Reserved</p>
                                    <p class="rf">by <a href="http://www.miguelpazo.com/">MiguelPazo</a></p>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE SOURCE -->
</html>