<div class="line-hor"></div>
<div class="box">
    <div class="border-right">
        <div class="border-left">
            <div class="inner">
                <h3>Movie<span> List</span></h3>
                <div id="contListMovies">
                <table class="tableList" id="listMovies" cellspacing="0">
                    <tr bgcolor="#fff">
                        <td>
                            
                        </td>
                        <td width="15%">
                            <b>Title</b>
                        </td>
                        <td>
                            <b>Code</b>
                        </td>
                        <td>
                            <b>Category</b>
                        </td>
                        <td>
                            <b>Type Audience</b>
                        </td>
                        <td>
                            <b>Type Product</b>
                        </td>
                        <td>
                            <b>Rental Days</b>
                        </td>
                        <td>
                            <b>Price</b>
                        </td>
                        <td>
                            <b>Cost</b>
                        </td>
                        <td>
                            <b>Invoice number</b>
                        </td>
                        <td>
                            <b>Date of purchase</b>
                        </td>
                        <td>
                            <b>Status</b>
                        </td>
                    </tr>                   
                </table>
                </div>
                <br/>
                <br/>
                <br/>
                <div class="wrapper"> 
                    <a href="/movies/new" class="link2"> 
                        <span> <span>New</span> </span> 
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>