<div class="line-hor"></div>
<div class="box">
    <div class="border-right">
        <div class="border-left">
            <div class="inner">
                <h3>Re<span>nt</span></h3>
                <form id="contacts-form" action="#">
                    <fieldset> 
                        Details Movie
                        <br/>
                        <br/>
                        <div class="field">
                            <label>Cod Movie:</label>
                            <input type="text" value=""/>
                        </div>
                        <div class="field">
                            <label>Name Movie:</label>
                            <input type="text" value=""/>
                        </div>
                        <div class="field">
                            <label>Category Movie:</label>
                            <input type="text" value=""/>
                        </div>
                        <div class="field">
                            <label>Type Audience:</label>
                            <input type="text" value=""/>
                        </div>
                    </fieldset>
                    <fieldset>
                        Details Client
                        <br/>
                        <br/>
                        <div class="field">
                            <label>Firts Name:</label>
                            <input type="text" value=""/>
                        </div>
                        <div class="field">
                            <label>Last Name:</label>
                            <input type="text" value=""/>
                        </div>
                        <div class="field">
                            <label>Code:</label>
                            <input type="text" value=""/>
                        </div>
                        <div class="field">
                            <label>Effective Date:</label>
                            <input type="text" value=""/>
                        </div>
                    </fieldset>
                        <div class="wrapper"> 
                            <a href="#" class="link2"> 
                                <span> <span>Send</span> </span> 
                            </a> 
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>